export const JPotrosConceptosNoJustificanErogaciones = [
    "IMPUESTOS DETERMINADOS NO DEDUCIBLES DEL PERÍODO FISCAL",
    "DONACIONES Y/O DISPOSICIONES DE FONDOS O BIENES A FAVOR DE TERCEROS",
    "RESULTADO NEGATIVO POR VENTA DE ACCIONES Y TÍTULOS SIN COTIZACIÓN",
    "RESULTADO NEGATIVO POR VENTA DE ACCIONES Y TÍTULOS CON COTIZACIÓN",
    "RESULTADO NEGATIVO POR VENTA DE MONEDA EXTRANJERA",
    "RESULTADO NEGATIVO POR VENTA DE BIENES REGISTRABLES",
    "VALOR LOCATIVO",
    "INGRESOS PRESUNTOS",
    "AMORTIZACIÓN ACUMULADA DE LOS BIENES DADOS DE BAJA",
]
export const pFinal = [

]
export const RentasExentas = [
    "INGRESOS POR DEPÓSITOS EN ENTIDADES FINANCIERAS DEL PAÍS",
    "DIVIDENDOS DISTRIBUIDOS POR SOCIEDADES DEL PAÍS",
    "RESULTADO POR LA VENTA DE ACCIONES Y TÍTULOS",
    "OTRAS GANANCIAS Y/O INGRESOS EXENTOS O NO GRAVADOS DE LA PRIMERA CATEGORÍA",
    "OTRAS GANANCIAS Y/O INGRESOS EXENTOS O NO GRAVADOS DE LA SEGUNDA CATEGORÍA",
    "GANANCIAS PROVENIENTES DEL MONOTRIBUTO",
    "RESULTADO POR LA VENTA DE MONEDA EXTRANJERA",
    "INGRESOS PROVENIENTES DE PREMIOS, SORTEOS Y JUEGOS DE AZAR",
    "GANANCIAS Y/O INGRESOS EXENTOS POR APLICACIÓN DE UN TRATADO INTERNACIONAL",
    "RESULTADO POR LA VENTA DE INMUEBLES",
    "RESULTADO POR LA VENTA DE RODADOS",
    "RESULTADO POR LA VENTA DE BIENES INTANGIBLES",
    "OTRAS GANANCIAS Y/O INGRESOS EXENTOS O NO GRAVADOS",
]
export const JPBienesRecibidos = [

]
export const JPGananciasNoImplicanErogaciones = [
    "AMORTIZACIONES DEL EJERCICIO DE LA TERCERA CATEGORÍA CORRESPONDIENTE A EMPRESAS UNIPERSONALES INCLUYE AMORTIZACIONES DE CADA CATEGORÍA)",
    "AMORTIZACIONES DE BIENES DE USO",
    "DIFERENCIA DE GASTOS DE MANTENIMIENTO PRESUNTOS DE INMUEBLES (CUANDO ÉSTOS SUPERAN A LOS GASTOS DE MANTENIMIENTO REALES).",
    "DEDUCCIÓN DE GASTOS POR REGALÍAS PERCIBIDAS EN CASO DE TRANSFERENCIA DEFINITIVA DE BIENES.",
]
export const JPotrosConceptosjustificanErogaciones = [
    
]
export const pInicial = [

]